services:
  - type: web
    name: ak-mobile-shop-backend
    plan: free
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: PORT
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPER_ADMIN_USERNAME
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
